### ISSUE TITLE
Create development branch

### ISSUE THREAD

**Issue by blundell** [novoda/simple-easy-xml-parser#12]
So we can have live code and merge pull requests onto develop

**Comment by blundell** [comment]
and with the current thinking should probably have a `release` branch and keep `master` to develop upon

**Comment by stefanhoth** [comment]
@blundell Why divert from the normal git flow model?

**Comment by blundell** [comment]
you mean with my latest comment? This is our current practice on current project and works well. No so much for you?

**Comment by stefanhoth** [comment]
My take on it is: Using develop as integration branch (set as the repo default) and master for the release branch is what most people would expect anyway so I think this has less cognitive overhead, imho.

**Comment by blundell** [comment]
I have the same argument but for the opposite :-) those who dev (but no idea about gitflow) always expect to be pushing / merging into master.  Further having the other branch as `release` makes it obvious what that branch is for (same argument could be had for `develop`) - less changes about changing repo default because `master` is default naturally.  :-)

**Comment by ouchadam** [comment]
+1 for release/master, it's the same gitflow just with different names.

W also get lots of people opening PRs against master even when the readme says to use `develop`.

**Comment by stefanhoth** [comment]
@ouchadam I think that only happens if the "main branch" is not set to develop in the repo settings of GitHub. But ok, I'll bow to the majority decision.

**Comment by xrigau** [comment]
https://github.com/novoda/simple-easy-xml-parser/tree/release
