### ISSUE TITLE
Add documentation for the main classes

### ISSUE THREAD

**Issue by xrigau** [novoda/simple-easy-xml-parser#17]

**Comment by JorgeCastilloPrz** [comment]
It would be really nice to add simple README documentation with the most common use cases. Users feel better if they can find their 90 percent of times wanted code just by reading README a little bit.

**Comment by malmstein** [comment]
:+1: @JorgeCastilloPrz

**Comment by blundell** [comment]
Done! 

https://github.com/novoda/simple-easy-xml-parser/blob/master/README.md
