### ISSUE TITLE
Align code convention

### ISSUE THREAD

**Issue by Mecharyry** [novoda/simple-easy-xml-parser#29]
Noticed in the test module. Three conventions are being used when naming methods:
- camelCase
- under_scores
- SomeStrange_mixture_of_the_two. 

Need to decide on the convention for this project and then implement.

**Comment by xrigau** [comment]
:-1: @ouchadam

**Comment by blundell** [comment]
was so right so long ago, sick magic

**Comment by blundell** [comment]
a year in the making we're going with `camelCaseGiven_camelWhen_camelThen()` and will change tests as we come across them
