### ISSUE TITLE
AndroidStudio: failed to find library

### ISSUE THREAD

**Issue by homj** [novoda/simple-easy-xml-parser#33]
I was just trying to add this library to my AndroidStudio-project, but i encountered this problem:

*Error:Failed to find: com.novoda.sexp:core:1.0.3*

I followed the description precisely, but somehow i can't add this library.
I'm still pretty new to gradle, so maybe I'm just too blind to see the problem.

Anyways, I would really appreciate if someone could point me to a solution =)

**Comment by ouchadam** [comment]
thanks for pointing this out! There's a mistake in the readme I'll fix it now :100:
