### ISSUE TITLE
Website not reachable

### ISSUE THREAD

**Issue by johnjohndoe** [novoda/simple-easy-xml-parser#34]
The linked website `http://novoda.github.io/SimpleEasyXmlParser/` returns 404.

**Comment by xrigau** [comment]
:+1:

@charroch @blundell anyone can fix this?

![screen shot 2015-02-09 at 14 39 04](https://cloud.githubusercontent.com/assets/1626673/6108255/6bcbb61c-b069-11e4-938c-8bd9bb3e4f01.png)

**Comment by blundell** [comment]
oh man our website diiiied

**Comment by blundell** [comment]
website branch is out of date and not up with latest standards 

https://github.com/novoda/simple-easy-xml-parser/blob/gh-pages

deleted the link and deleted the branch

![screen shot 2015-02-10 at 09 09 34](https://cloud.githubusercontent.com/assets/655860/6124344/8c462076-b104-11e4-9bdf-cc0b956af336.png)
