### ISSUE TITLE
Unclosed streams

### ISSUE THREAD

**Issue by blundell** [novoda/simple-easy-xml-parser#36]
I've just noticed in our public API we create new streams but we don't close them.

Does the implementation close them? or is this a bug?

https://github.com/novoda/simple-easy-xml-parser/blob/master/sexp/src/main/java/com/novoda/sexp/SimpleEasyXmlParser.java#L27

The public interface can also be passed a stream, then it is up to the client to close their own stream - so this complicates it for us to know if to close or not.

**Comment by joetimmins** [comment]
All of the streams that our library creates are instances of ByteArrayInputStream. This is from the ByteArrayInputStream docs.

> Closing a ByteArrayInputStream has no effect. The methods in this class can be called after the stream has been closed without generating an IOException. 

https://docs.oracle.com/javase/7/docs/api/java/io/ByteArrayInputStream.html#close%28%29

Also, if you look at the source code for this class's close() method in API level 23, there is no method body whatsoever. It's completely empty. So there's no need to call close() here.

As pointed out in the previous comment, any InputStreams that are passed into the library from client code should be closed by that client, so there's no need for us to close those, either.

**Comment by blundell** [comment]
👍  winning
