### ISSUE TITLE
Inflate animated-vector xml parsed

### ISSUE THREAD

**Issue by andres934** [novoda/simple-easy-xml-parser#44]
im have an animated-vector in a string, i can parsed with your lib but then how can i inflate, already lost 1 week trying to inflate it, its no a entire view, its just an element in simple view, it can be done with your lib?

**Comment by blundell** [comment]
ummmmm, @rock3r @alexstyl is this the same question I asked the other week, and is the answer no? 😄

**Comment by alexstyl** [comment]
AFAIK Animated vector drawables can only be created through XML. Even if you have the content of the vector drawable as a string and you do manage to create an XML file out of that, there is no way to 'feed' that to the framework so that it does it's work with it.
